### PR TITLE
Use proper return and initialize value

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
In Travis I saw a few warnings and these should be easy enough to fix.

### CODE REVIEW

**Comment by didier-wenzek** [comment]
Thanks. The tests are now failing on the check I added this morning (i.e. invoking the callback after a full GC). I will see this evening what is going on.

**Comment by Leonidas-from-XIV** [comment]
Yes, they do that on `master` as well. I don't quite know why it would fail on `4.02` but not on `4.09`.

**Comment by Leonidas-from-XIV** [comment]
I was curious since they always fail in the same way whether it is version-dependent and [tested all versions from 4.02 to 4.10](https://travis-ci.org/Leonidas-from-XIV/ocaml-kafka/builds/657430380). Seems like the behaviour changed at some point.

**Comment by didier-wenzek** [comment]
This seems related to that issue https://github.com/ocaml/ocaml/pull/8656 which has been released with the 4.09.

**Comment by didier-wenzek** [comment]
One option is to check the proper root registration only for the versions of OCaml after 4.09.

```
let major,minor = Scanf.sscanf Sys.ocaml_version "%d.%d" (fun x y -> (x,y)) in
   if major >=4 && minor >= 9 then Gc.full_major ();
```

**Comment by Leonidas-from-XIV** [comment]
Oh, that's a very good find and would explain it!

Another option could be to just use `caml_register_global_root` for now, since except for being a bit slower it should work just as fine. And maybe use generational roots only in 4.08+ if necessary.

**Comment by didier-wenzek** [comment]
Using `caml_register_global_root` works fine. I have no idea what can be the performance impacts, (proportional to the size of the tree reachable from the root?) but I believe we can start with this. The better would be to have a compiler switch, but I'm not sure this worth the value.

**Comment by Leonidas-from-XIV** [comment]
I've tested this fix [on the whole supported range of compilers](https://travis-ci.org/Leonidas-from-XIV/ocaml-kafka/builds/657668753) and it seems to work fine. The version switch in C is not too painful, since it is contained in these two functions, but I can also deduplicate the logic if desired.

**Comment by didier-wenzek** [comment]
Thanks. Agree: the switch in C is readable since really localized.

I will merge once the callback assignment moved to the proper place.

**Comment by Leonidas-from-XIV** [comment]
Ah, true. Looks like it was too early in the morning for me. I've amended the commit to not trash the history too much.

**Pull request merged**
