### PR TITLE
Split Lwt part into separate OPAM package

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
Currently the Lwt bindings are optional and only built when Lwt is installed. This also means that a client package that depends on them, has to depend on `kafka` and a compatible version of `lwt` so the current guideline in OPAM is to have separate subpackages with hard dependencies, so users can depend on `kafka_lwt` and get it installed.

The other reason for splitting is that I am considering contributing Async bindings, and Async is a rather heavy dependency that I wouldn't want to add to the "blocking" core package, so making that a separate package might be nicer for users in any case.

The downside is that that means that the `kafka.lwt` `public_name` has to be changed to `kafka_lwt`, to make it match up with the OPAM package (which can't have dots).

I've generated the OPAM files with `dune`, but `dune` does not support generating `depexts` yet, so I disabled it again and edited in the depexts manually.

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
Thanks to @rgrinberg I figured out how I can make `dune` generate the right `depext` fields, so if you're interested I can submit the code that autoupdates the `opam` files. The only downside is that it requires `dune` `>= 1.10`, but that should not be much of an issue since dune 1.x is pretty compatible.

**Comment by didier-wenzek** [comment]
Thanks @Leonidas-from-XIV. I'm happy to merge your pull request. Opening the ability to have an Async binding is great!

I'm also happy with `dune >= 1.10`. Before I merge, do you prefer to commit first an update dune file?

**Comment by Leonidas-from-XIV** [comment]
@didier-wenzek Thanks for your quick response! I have submitted the updated `dune-project` file which generates the `opam` files automatically, so if you feel like this is acceptable to merge, please go ahead.

**Comment by Leonidas-from-XIV** [comment]
Thanks! 🎉

**Comment by didier-wenzek** [comment]
To publish it on opam, I will take a bit more time though. I'm not used to this and it always takes me some time to double-check the different steps!

Thanks for your contribution.

**Comment by Leonidas-from-XIV** [comment]
No worries, this is not really urgent, but now I have a place to base my async work on :-)

For releases I can very much recommend `dune-release`, which handles creating proper tarballs, unpacking and testing them (to prevent publishing broken releases), uploading them to GitHub, auto-generating API docs and uploading these to GitHub, as well as creating opam files suitable to publish to `opam-repository` (basically, the same files, but with the checksums and URLs of the generated and uploaded tarballs).

**Comment by didier-wenzek** [comment]
Thanks for the advice.

If you have any questions or propositions to improve the API. Let me know. I designed it for my own usage and would be glad to discuss and confront a different point of view.

**Pull request merged**
